// <auto-generated />
namespace Reservas_Local.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class localConUbi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(localConUbi));
        
        string IMigrationMetadata.Id
        {
            get { return "202111030355127_localConUbi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
